import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"

import SideBar from "@features/landing/components/composites/SideBar"
import { QueryProvider } from "@features/query/QueryProvider"

import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <div className="flex min-h-screen flex-col 2xl:flex-row">
            <aside className="shrink-0 2xl:w-[228px]">
              <SideBar />
            </aside>
            <main className="w-full">{children}</main>
          </div>
        </QueryProvider>
      </body>
    </html>
  )
}
