import "./globals.css"

import { Geist, Geist_Mono } from "next/font/google"

import type { Metadata } from "next"
import { QueryProvider } from "@features/query/QueryProvider"
import SideBar from "@features/landing/components/composites/SideBar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <div className="m-auto flex min-h-screen w-full max-w-[1440px] flex-col justify-between px-4 md:flex-row md:gap-6 md:px-8 xl:px-12">
            <aside className="h-[80px] shrink-0 md:w-[210px]">
              <SideBar />
            </aside>
            <main className="w-full md:max-w-[calc(100%-210px-36px)]">
              {children}
            </main>
          </div>
        </QueryProvider>
      </body>
    </html>
  )
}
